# Generated by Django 5.2.6 on 2025-11-10 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Room name must contain only letters and digits.', regex='^[A-Za-z0-9\\s]+$')]),
        ),
    ]
