# Generated by Django 5.2.6 on 2025-11-10 12:32

import ConferenceApp.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='theme',
            field=models.CharField(choices=[('cs_ai', 'Computer Science & Artificial Intelligence'), ('sci_eng', 'Science & Engineering'), ('social_edu', 'Social Sciences & Education'), ('interdisciplinary', 'Interdisciplinary Themes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_list', to='ConferenceApp.conference'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.CharField(help_text='Séparez par des virgules (max 10)', max_length=500, validators=[ConferenceApp.models.submission.validate_keywords]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
