# Generated by Django 5.2.6 on 2025-11-10 12:32

import UserApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[UserApp.models.verify_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='This field must contain only letters, spaces or hyphens.', regex='^[A-Za-zÀ-ÿ\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='This field must contain only letters, spaces or hyphens.', regex='^[A-Za-zÀ-ÿ\\s-]+$')]),
        ),
    ]
